### ISSUE TITLE
[1.21.1] KubeJS Actually Addittions crash game

### ISSUE THREAD

**Issue by Periam** [AlmostReliable/kubejs-actuallyadditions#2]
### Minecraft Version

Minecraft 1.21.1 

### Mod Version

KubeJS Actually Additions 1.21.1-0.2.1 (

### Describe the bug!

After installing the latest version of AA, the game does not load old or new worlds, but if the KubeJS for AA is disable the game works fine.

### Crash Report

https://pastebin.com/V2FSbkKR

### Log

https://pastebin.com/V2FSbkKR

### Additions and Modifications

Yes

### Additions and Modifications Description

Actually Additions 1.3.12 (actuallyadditions)
Just Enough Items 19.21.0.247 (jei)
KubeJS 2101.7.1-build.181 (kubejs)
KubeJS Actually Additions 1.21.1-0.2.1 (kubejs_actuallyadditions)
Minecraft 1.21.1 (minecraft)
NeoForge 21.1.83 (neoforge)
Rhino 2101.2.6-build.58 (rhino)

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
Thank you for the report. They removed a recipe type. Will be fixed in a bit.
